### ISSUE TITLE
Your core/config.php file is not writeable.

### ISSUE THREAD

**Issue by Legomix13** [NamelessMC/Nameless#197]
I am setting up the site and when I put the DB I get this: "Your core/config.php file is not writeable. Please check your file permissions."
What can I do?

**Comment by samerton** [comment]
Depends on your server's OS, if you're running Ubuntu/Debian try

chown -R www-data:www-data /var/www/html

**Comment by Legomix13** [comment]
Cent OS 7

**Comment by Schwertspize** [comment]
Do chown on the directory where you uploaded the source to

**Comment by Legomix13** [comment]
Oke

**Comment by Legomix13** [comment]
And that "www-data:www-data"?

**Comment by samerton** [comment]
I could be wrong as I've not used CentOS before, but try apache:apache instead of www-data:www-data.

**Comment by Legomix13** [comment]
Not work

**Comment by samerton** [comment]
What is the command you typed?

**Comment by Legomix13** [comment]
chown -R apache:apache /var/www/html

**Comment by Legomix13** [comment]
Maybe we could talk on skype

**Comment by samerton** [comment]
The only thing I can suggest is double check your path (/var/www/html), is that where you uploaded the Nameless files to, or was that somewhere else?

**Comment by Legomix13** [comment]
Its that path (/var/www/html)

**Comment by Schwertspize** [comment]
are you using apache?

**Comment by Legomix13** [comment]
yes

**Comment by Schwertspize** [comment]
well, as i read it, try `chown -R httpd:httpd /var/www/html`

hope its fixed now

**Comment by Legomix13** [comment]
It say invalid user

**Comment by Schwertspize** [comment]
can you run `ls -al /var/www/html`

and, if necessairy try running `chmod -r 644 /var/www/html`

**Comment by samerton** [comment]
I've taken a look, and everything I can find suggests that

chown -R apache:apache /var/www/html

should work.

Are you logged in as root to type in that command?

If so, can you try 

ls -ld /var/www/html

and see what the user/group associated with the folders/files within are?

**Comment by Legomix13** [comment]
![captura](https://cloud.githubusercontent.com/assets/13416327/15455866/9b90c51e-2060-11e6-8aea-734ba592bda5.PNG)
I tried that but still not workin and,yes i'm root

**Comment by samerton** [comment]
The problem looks to be with the command you're using. Instead of "root:apache", make sure it's "apache:apache" in the chown.

**Comment by samerton** [comment]
The last command suggests that the permissions are correctly set up (the user and group are both set to apache), which means PHP should have write access to the folder. Can you try with the Nameless installation again?

**Comment by Legomix13** [comment]
I'm installing it but not work

**Comment by Legomix13** [comment]
Installing: "Your core/config.php file is not writeable. Please check your file permissions."

**Comment by samerton** [comment]
Unfortunately I'm out of ideas, as everything seems to be in order.

**Comment by Legomix13** [comment]
You have skype?

**Comment by Legomix13** [comment]
I install it on my pc,i'm going to upload it

**Comment by samerton** [comment]
I don't have a Skype account for support sorry.

One last thing I can suggest is:

chown -R nobody:nobody /var/www/html

**Comment by Legomix13** [comment]
I upload it from my pc and I can't access phpmyadmin and i'm getting: "HTTP ERROR 500"

**Comment by samerton** [comment]
Check your server's Apache logs for errors, I'm not sure where these are.

**Comment by Legomix13** [comment]
Did you have any way to talk? Maybe its easyer

**Comment by samerton** [comment]
I don't have any other methods of support at the moment sorry.

**Comment by Legomix13** [comment]
Where is the apache log?

**Comment by samerton** [comment]
I don't know, this depends on your installation. The answers to [this question](http://serverfault.com/questions/189205/where-can-i-find-apache-error-log-on-centos) will help you locate the file.

**Comment by Legomix13** [comment]
Maybe you can help me installing php mysql and all from 0 with ubuntu or fedora...

**Comment by samerton** [comment]
Sure, I can set everything up for you on Ubuntu/Debian if you want.

**Comment by Legomix13** [comment]
Yes please

**Comment by samerton** [comment]
If you send me an email (on my GitHub profile) or a private message if you have an account on SpigotMC, I can do so.

**Comment by Legomix13** [comment]
Sure

**Comment by Legomix13** [comment]
What its you spigot profile?

**Comment by samerton** [comment]
[Samerton](https://www.spigotmc.org/members/samerton.10676/)

**Comment by Legomix13** [comment]
I send a PM

**Comment by samerton** [comment]
Thanks, I'll close this now as it's a server configuration issue instead of a Nameless issue, and I'll reply to your PM.

**Comment by Legomix13** [comment]
Sorry for reopening this another time but I found the solution,just execute this:

chcon -t httpd_sys_rw_content_t /var/www/html/ -R

Then it will work!!

**Comment by orangcrsh** [comment]
> Sorry for reopening this another time but I found the solution,just execute this:
> 
> chcon -t httpd_sys_rw_content_t /var/www/html/ -R
> 
> Then it will work!!

Thanks a lot ! Saved my life.
