### ISSUE TITLE
Lots of stuff. Sorry, I'm picky. 

### ISSUE THREAD

**Issue by Pugabyte** [NamelessMC/Nameless#264]
Small bugs: 
- [Calendar window is partially blocked by navbar](http://i.imgur.com/VINyJ70.png).
- [Forums box has an ugly category format](http://i.imgur.com/EHC6cXS.png)

Version 1.0.10, theme Darkly

Error: Tried to send a PM to someone, got this error: _SQLSTATE[HY000]: General error: 1364 Field 'content' doesn't have a default value_. I probably config'd something wrong, but not sure what.

And "a few" feature requests. There are duplicates, but I'm just going to say them again. I'm also aware I can edit the source/database to change some of these (and already have), but this can be for general future improvements, for users who don't know how to edit the source. :)
## Applications
- Multiple applications 
- Better support for different question types, like radio buttons, calendar windows, etc.
- Restrict an application to certain ranks, like a forum.
## Nav Bar
- Ability to re-name built in pages, such as "Play"
- Ability to restrict a page's nav bar link visibility based on rank
- Custom redirect links (See my manual solution in #249) 
- More dropdowns 
## Infractions
- Add option to disallow players who are banned in-game to post a new thread, and only allow them to appeal via application (obviously, this would have to come after the application improvements)
- Also add ability to restrict the "Infractions" footer link to certain ranks.
## Ranks
- Sync ranks ingame with vault groups
- Ability to add more than one rank to a user
- Custom page for a group (ability to redirect (e.g. to a wiki))
- Ability to re-order the ranks (changing the ID in the database (and don't forget about users too (and the initial rank you get assigned when you sign up))), and the same for the nav bar pages. 
## Users
- Format player's uuid with dashes 
- Ability to change user's banner on their profile page (Maybe there already is a way? Am I missing something?)
- **Promote someone ingame when they sign up!!**

Thank you for reading. I love the website so far, don't get me wrong, I just would like to help improve it a little bit. :)

I will very likely be posting more bugs/suggestions as I come across them / discuss with my staff team.

**Comment by Schwertspize** [comment]
Pm error is probably an empty content? 😮 

Restrict to ranks.... It doesn't change anything if you accept it, afaik you have to change the group yourself

**Comment by samerton** [comment]
Thanks for these, here are my initial thoughts:

- Calendar window is partially blocked by navbar:
Should be fixed in df7cf761cc9be80feb64432c2484a22cdc3720fc

- Forums box has an ugly category format
Should be fixed in c82c28b66d3a78822cfbe85dbcafd2566c2ccd41

- PM error
I've not seen this before, sounds like it could be caused by MySQL Strict mode. Can you try disabling it with the SQL command `SET sql_mode = '';`

- Applications
Applications are due a large revamp, as they're still (pretty much) unchanged from the early pre-releases. I can implement your suggestions in the revamp, which will probably come after the 1.1 release.

- Nav Bar
It's currently possible to rename a page, although without changing the URL, by editing the language value within the `$navbar_array` section of styles/language/*Language*/language.php. Version 2.0, which is still in very early development, will be able to support custom page links much better, and redirect pages themselves should be added to 1.x in the near future.

- Infractions
Banned user restrictions would probably come with the ingame plugin, as it'll be possible to set the forum rank of an ingame banned user.

- Ranks
Synchronisation with ingame groups are planned, and will be included in the upcoming Nameless plugin. Secondary groups, a group hierarchy and more permissions (ie with custom pages and addons) are also planned for somewhere down the line, although I'm not sure when they'll be implemented.

- Users
I can add a different field to display UUIDs with dashes, but the actual UUIDs stored in the database will remain without dashes. Changing profile banners per user has already been implemented in the 2.0 development versions, although you can change the default image by replacing **core/assets/img/profile.jpg** with an image of your choice. User promotion upon signup can also be implemented using the ingame plugin.

Thanks for the suggestions, and no need to apologise haha, they're really helpful for developers!

**Comment by PugaBear** [comment]
Awesome, thank you for the information. I will be customizing this website a lot over the next few weeks :)

One question- I would like to add a simple line of code to send a command to my MC server (simple to do with mark2) when a user successfully authenticates their account; I can figure out the code, I just need to know where to put it. I was looking at core/classes/Validate.php and pages/register.php, but I'm not entirely sure where it would best fit.

**Comment by samerton** [comment]
@PugaBear 
Sorry for the late reply.
Once a user has validated their account, the file which handles this is **pages/validate.php**. You'd need to add any custom code just after line 18 of that file.

As for the plugin, the official plugin is still in development. The registration plugin is third party and is unofficial.

**Comment by PugaBear** [comment]
@samerton 
Thats okay, thank you :)

I'm still having troubles with PMing. I tried setting SQL mode to '' (Logged onto phpMyAdmin, went to the database overview, clicked "SQL" and executed query there), still getting the same error.

**Comment by samerton** [comment]
@PugaBear 
[This](https://support.kayako.com/article/472-how-do-i-disable-mysql-strict-mode-on-the-server) might be able to help with disabling MySQL strict mode, unfortunately it's something I can't help too much with.

**Comment by PugaBear** [comment]
@samerton Didnt change anything

**Comment by samerton** [comment]
@PugaBear 
Can you manually remove the "content" column from the "nl1_private_messages" table, using phpMyAdmin?

**Comment by PugaBear** [comment]
@samerton Eh, well, the column doesn't exist. None do. http://i.imgur.com/kg8dHnn.png Didn't notice that before :P

**Comment by samerton** [comment]
@PugaBear 
Are you able to see it in the "Structure" tab?

**Comment by PugaBear** [comment]
@samerton Oh, yes I am, my bad

**Comment by JustOneMoreBlock** [comment]
Hello,

Not sure if you would consider this. However, I've been using XenForo for many years and there is such a great add-on for unlimited applications called "SimpleForms".

Recently, the company LiquidPro closed and they made the addon free and placed under the GNU GPLv3 License.

https://github.com/jljr222/xenforo-simple-forms

Basically, what this guy wants and I'm sure many others would be this addon. However, a little bit of code modification, you might be able to use this addon to help further development.

Just a thought.

**Comment by PugaBear** [comment]
@samerton I've been playing with the private messages table, trying to get it to work. I allowed 'content' to be null, and then got this error:
_SQLSTATE[01000]: Warning: 1265 Data truncated for column 'sent_date' at row 1_

I'm really at a loss here :\

**Comment by samerton** [comment]
@JustOneMoreBlock Thanks for the link, I'll take a look :)

@PugaBear The SQL error should be fixed in [this commit](https://github.com/NamelessMC/Nameless/commit/774b9ce6ff85652b281828455fdde1d0f55605d6), if you replace the contents of **pages/user/messaging.php** with [this code](https://raw.githubusercontent.com/NamelessMC/Nameless/master/pages/user/messaging.php), it will be safe to drop the "content" and "sent_date" columns altogether.

**Comment by PugaBear** [comment]
Thanks, that worked :)

**Comment by ryancito02** [comment]
Since this seems to be about issues and bugs, to reference an earlier issue I had, about the resizing of header image. How would one make the header image go into very top and stretch to sides, and make the NAV BAR transparent and positions at the bottom of header image, which is now covering up all of top? I know I will have to go into the themes and change it so that NAV BAR is transparent, however, the other things I believe lie in the PHP and HTML files. Can anyone give me a pointer on which files to look in and what statements to change to accomplish my goal?

**Comment by Derkades** [comment]
These issues are for v1 and v1 probably won't get much if any development anymore. Most of these issues are probably fixed in v2, if some are not please create new issues.
